[features]
seeds = false
skip-lint = false
[programs.localnet]
closing_accounts = "3v46VFd9BqVmnEK8TkT3iYVJPJpXget3jg4hMA1FbgZp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
